- .travis.yml
- lib/humanfilesize.ts
- package-lock.json
- package.json
- test/humanFileSize.test.js
* Move tests from the Nextcloud server repo here
* Replace OC.getCanonicalLocale with the one from @nextcloud/l10n
> Test formatFileSize and make it more independent from server

- .github/workflows/command-rebase.yml
- .github/workflows/fixup.yml
- .github/workflows/npm-publish.yml
> Add useful workflows

- .github/workflows/documentation.yml
https://nextcloud.github.io/nextcloud-files/
> Add auto-deploy documentation

- jest.config.js
> chore(tests): exclude logger utils from coverage

- CHANGELOG.md
- package-lock.json
- package.json
> chore(release): 3.0.0-beta.6

- package-lock.json
- package.json
- vite.config.ts
This also fixes the problem with `node:` protocol unknown in server.
> fix: Move to `@nextcloud/vite-config` after package was transfered

- .github/workflows/documentation.yml
- .github/workflows/npm-publish.yml
- package.json
Signed-off-by: Louis Chemineau <louis@chmn.me>
> Remove permission check in publish workflows

- CHANGELOG.md
- package-lock.json
- package.json
So we can update server and fix the quota display issue on current master.
> chore: Prepare new beta release

- __tests__/dav/dav.spec.ts
- __tests__/files/file.spec.ts
- __tests__/files/folder.spec.ts
- __tests__/files/node.spec.ts
- __tests__/newFileMenu.spec.ts
- lib/dav/dav.ts
- lib/files/node.ts
- lib/files/nodeData.ts
Reverts nextcloud-libraries/nextcloud-files#789
> Revert "feat!: add NodeData.encodedSource "

- CHANGELOG.md
- package-lock.json
- package.json
[Full Changelog](https://github.com/nextcloud-libraries/nextcloud-files/compare/v3.0.0-beta.24...v3.0.0-beta.25)
* feat(files): add encodedSource by @skjnldsv in https://github.com/nextcloud-libraries/nextcloud-files/pull/794
cc @kesselb
> 3.0.0-beta.25

- CHANGELOG.md
- package-lock.json
- package.json
We need a release to resolve https://github.com/nextcloud/server/issues/44173
> chore: Prepare 3.1.1 release

- lib/dav/dav.ts
- package-lock.json
- package.json
- For https://github.com/nextcloud/server/issues/44613
> feat(dav): Make getFavoriteNodes cancelable

- CHANGELOG.md
- package-lock.json
- package.json
* fix: Update NPM version to LTS version 10
* Updated development dependencies
> chore: Prepare 3.2.1 release

- .github/workflows/node.yml
- package-lock.json
- package.json
- vite.config.ts
https://docs.codecov.com/docs/javascript-bundle-analysis
> feat(ci): add codecov bundler

- __tests__/newFileMenu.spec.ts
- lib/newFileMenu.ts
Required for the last part of: https://github.com/nextcloud/server/issues/43728
> feat(new-menu): Allow to set the category for entries

- package-lock.json
- package.json
Fix a dependabot warning for development dependencies.
> fix: Update development dependencies

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Prepare v3.5.1 release

- __tests__/test-global-setup.ts
- vitest.config.ts
Fixes errors like: ![image](https://github.com/user-attachments/assets/3a5de4f7-3c43-4948-9e43-d5724195c6cd)
> test: Ensure time zone dependent tests run identically across environments

- __tests__/files/node.spec.ts
- lib/files/node.ts
Signed-off-by: John Molakvoæ (skjnldsv) <skjnldsv@protonmail.com>
> fix: also validate Node data on setter 

- __tests__/files/node.spec.ts
- lib/files/node.ts
Needed for https://github.com/nextcloud/server/issues/2736
> feat: allow changing Node mime type
