nextcloud-libraries/nextcloud-files

- lib/humanfilesize.ts
[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.
> Replace deprecated String.prototype.substr()

- __tests__/newFileMenu.spec.ts
- lib/index.ts
- lib/newFileMenu.ts
Since on the same initiated instance, the context can change, we need a way to filter Entries
e.g.
1. Open the Files app (the `NewFileMenu` gets initialized)
2. See that you can create files
3. Navigate to a shared read-only folder
4. The context change, the menu list should be different
It was a leftover from th server API where the api itself was in charge of creating the file/folder. So it needed to know what type it was. But now we let that to the Entry registration via the `handler` prop.
> Add context to getEntries

- __tests__/humanFileSize.spec.ts
- __tests__/index.spec.ts
- __tests__/newFileMenu.spec.ts
- lib/humanfilesize.ts
- lib/newFileMenu.ts
- `parseFloat` always strip the `.0` from the number, we don't need a dedicated check for it. I added some tests for it to make sure we don't have a regression: 100% coverage now
- 100% coverage on the `newFileMenu` too
> Cleanup, remove unnecessary check and move to 100% coverage

- lib/index.ts
> Also use context from exposed method

- __tests__/newFileMenu.spec.ts
- lib/newFileMenu.ts
> Fix templateName usage and errors strings

- __tests__/files/file.spec.ts
- __tests__/files/folder.spec.ts
- __tests__/files/node.spec.ts
- __tests__/humanFileSize.spec.ts
- __tests__/index.spec.ts
- lib/files/file.ts
- lib/files/fileType.ts
- lib/files/folder.ts
- lib/files/node.ts
- lib/files/nodeData.ts
- lib/index.ts
- lib/permissions.ts
```js
new File({
source: 'https://cloud.domain.com/remote.php/dav/files/emma/Photos/picture.jpg',
id: 1234,
owner: 'emma',
mime: 'image/jpeg',
crtime: new Date(),
mtime: new Date(),
size: 28942873,
permissions: Permission.ALL,
attributes: {
hasPreview: true,
},
})
```
> Add File and Folder API

- package-lock.json
- package.json
Fix master 
https://github.com/nextcloud/nextcloud-files/actions/runs/4007681471
```
> npm ci
added 505 packages, and audited 506 packages in 6s
37 packages are looking for funding
run `npm fund` for details
found 0 vulnerabilities
> npm run build:doc
> typedoc --out dist/doc lib && touch dist/doc/.nojekyll
node_modules/@types/node/globals.d.ts:85:13 - error TS2403: Subsequent variable declarations must have the same type.  Variable 'AbortSignal' must be of type '{ new (): AbortSignal; prototype: AbortSignal; abort(reason?: any): AbortSignal; timeout(milliseconds: number): AbortSignal; }', but here has type '{ new (): AbortSignal; prototype: AbortSignal; }'.
85 declare var AbortSignal: {
~~~~~~~~~~~
node_modules/typescript/lib/lib.dom.d.ts:2071:13
2071 declare var AbortSignal: { …
```
> chore(deps): fix deps and docs build

- __tests__/files/file.spec.ts
- __tests__/files/folder.spec.ts
- __tests__/files/node.spec.ts
- lib/files/node.ts
- lib/files/nodeData.ts
This should ensure we are working from a specific point
This makes sense for most dav ressources
```js
const file = new File({
source: 'https://cloud.domain.com/remote.php/dav/files/emma/Photos/Berlin/picture.jpg',
mime: 'image/jpeg',
owner: 'emma',
root: '/files/emma',
})
file.basename: 'picture.jpg'
file.extension: '.jpg'
file.dirname: '/Photos/Berlin'
file.path: '/Photos/Berlin/picture.jpg'
file.root: '/files/emma'
file.isDavRessource: true
```
> feat(node): allow and recommend to provide a specific root

- CHANGELOG.md
- package-lock.json
- package.json
[Full Changelog](https://github.com/nextcloud/nextcloud-files/compare/v3.0.0-beta.6...v3.0.0-beta.7)
- feat\(node\): allow and recommend to provide a specific root [\#574](https://github.com/nextcloud/nextcloud-files/pull/574) ([skjnldsv](https://github.com/skjnldsv))
> 3.0.0-beta.7

- __tests__/fileAction.spec.ts
- __tests__/files/node.spec.ts
- __tests__/index.spec.ts
- __tests__/newFileMenu.spec.ts
- lib/fileAction.ts
- lib/files/node.ts
- lib/index.ts
RFC: https://github.com/nextcloud/server/issues/21835
``` ts
interface FileActionData {
id: string
displayName: (files: Node[], view) => string
iconSvgInline: (files: Node[], view) => string
enabled?: (files: Node[], view) => boolean
exec: (file: Node, view) => Promise<boolean>,
execBatch?: (files: Node[], view) => Promise<boolean[]>
order?: number,
default?: boolean,
inline?: (file: Node, view) => boolean,
renderInline?: (file: Node, view) => HTMLElement,
}
```
> feat(FileAction): add file action support

- __tests__/files/file.spec.ts
- __tests__/files/folder.spec.ts
- __tests__/files/node.spec.ts
- lib/files/node.ts
- lib/files/nodeData.ts
A bit more safeguards and fixes the `path` computation that goes with it
> fix: prevent invalid roots to be defined

- .github/workflows/documentation.yml
- package-lock.json
- package.json
~~@ChristophWurst do you know why `@nextcloud/l10n` is failing ?~~
> feat(actions): also test doc build on pull requests

- __tests__/files/file.spec.ts
- __tests__/files/folder.spec.ts
- __tests__/files/node.spec.ts
- lib/files/node.ts
```js
return this._data.permissions || Permission.READ
```
This fails if permissions = `NONE` (0)
> fix(node): default permissions should be NONE and fix undefined return

- __tests__/fileAction.spec.ts
- __tests__/humanFileSize.spec.ts
- __tests__/index.spec.ts
- __tests__/newFileMenu.spec.ts
- jest.config.js
- lib/index.ts
- package-lock.json
- package.json
- tsconfig.json
- window.d.ts
See https://github.com/nextcloud/nextcloud-router/pull/485
It makes testing on server difficult
> fix: Do not export the declaration of window.OC

- __tests__/files/node.spec.ts
- lib/files/node.ts
The id was never used before.
Now we fixed it!
> fix: fileid definition and fallback

- __tests__/files/node.spec.ts
- lib/files/nodeData.ts
We should be allowed to specify a property as undefined
> fix: allow undefined properties in File and Folder

- .eslintrc.js
- .eslintrc.json
- .github/dependabot.yml
- .npmignore
- jest.config.js
- package-lock.json
- package.json
- rollup.config.js
- tsconfig.json
* Drop unneeded .npmignore (`files` section of package.json overrides it anyways)
* Make package an ESM one (migrate config files to modules)
* ESLint currently does not support an esm config, so use the json config instead
* Use `bundler` as Typescript resolution as we use rollup anyways
* Update package lock file to version 3 as we use NPM 9 already
* Update versions inside package.json to match the package-lock updated ones
> chore: Cleanup package and make it a native ESM package

- __tests__/files/file.spec.ts
- lib/files/node.ts
Context:
1. In the files app, have a list of node with unknown mtime
2. the mtime column is hidden 
3. have an action updating a Node attribute
4. the mtime column suddenly appear because at least one node now have a valid mtime
Correct behaviour:
- the mtime column stays hidden and the mtime stays undefined
> fix: do not update mtime if not already defined

- __tests__/files/node.spec.ts
- lib/files/nodeData.ts
https://github.com/nextcloud/server/blob/ac2bc2384efe3c15ff987b87a7432bc60d545c67/lib/private/Files/Cache/FailedCache.php#L55-L62
> fix(node): allow negative file ids

- __tests__/fileListHeaders.spec.ts
- lib/fileListHeaders.ts
- lib/index.ts
- window.d.ts
Ref: https://github.com/nextcloud/server/pull/17482
It seems no one is using the footer API in years. I think it's time to drop it :shrug:
> feat: add FileListHeader

- __tests__/fileAction.spec.ts
- __tests__/fileListHeaders.spec.ts
- lib/fileAction.ts
- lib/fileListHeaders.ts
Otherwise if an app uses `getFileActions` or  `getFileListHeaders` BEFORE any other app registered one, the returned empty array will not point to the window reference and will not be reactive
> fix: headers and actions empty variable init

- __tests__/dav/dav.spec.ts
- lib/dav/dav.ts
* `davGetClient` should default to the DAV remote URL instead of including the users root (to allow SEARCH)
* `getFavoriteNodes` should work with any path
* Add missing documentation
Because especially the `getFavoriteNodes` function was copied from the files app, but there is no reason why it should be restricted in this library to only support favorites on `/` but not on other paths (also the documentation said it would do).
> fix(dav): Fix DAV functions to make work with them easier

- vite.config.ts
Increase the size a bit, but it's the only solution I've found :disappointed:
> fix: force bundle `is-svg`

- __tests__/files/file.spec.ts
- __tests__/files/node.spec.ts
- lib/files/node.ts
- lib/files/nodeData.ts
- lib/index.ts
```ts
/** This is a new node and it doesn't exists on the filesystem yet */
NEW = 'new',
/** This node has failed and is unavailable  */
FAILED = 'failed',
/** This node is currently loading or have an operation in progress */
LOADING = 'loading',
/** This node is locked and cannot be modified */
LOCKED = 'locked',
```
Makes it a bit more official instead of those weird hidden values
e.g https://github.com/nextcloud/server/blob/4e60b3c61e8e0699e341fb62f9f109d2525be5ab/apps/files/src/services/Files.ts#L65
> feat(files): add node status

- __tests__/humanFileSize.spec.ts
- lib/humanfilesize.ts
The default was previously on Nextcloud core set to true, so bytes were formatted using base 2. (But the wrong unit was used, e.g. 1024 byte were formatted as 1 KB). This reverts the default to format sizes using the binary format (1024 = 1 KiB).
> fix(formatFileSize): Fix default value for `binaryPrefixes`

- __tests__/humanFileSize.spec.ts
- lib/humanfilesize.ts
The function is migrated from Nextcloud core. It will parse a human readable file size, like `2 KiB` or `2 KB` to machine usable number of bytes. e.g. `2 KiB` => 2048 bytes, `2 KB` => 2000 bytes.
It also allows to force reading the number as binary prefix, meaning `2 KB` will be interpreted as 2048 bytes like on some systems were the incorrect unit is used.
> feat(parseFileSize): Added `parseFileSize` function to parse a human readable file size to number of bytes

- __tests__/dav/dav.spec.ts
- __tests__/files/file.spec.ts
- __tests__/files/folder.spec.ts
- __tests__/files/node.spec.ts
- __tests__/newFileMenu.spec.ts
- lib/dav/dav.ts
- lib/files/node.ts
- lib/files/nodeData.ts
After https://github.com/nextcloud/server/pull/40644 it's possible to delete, restore and favorite files with special characters like `#` but the displayed filenames are also encoded. 
This PR adds a new property `encodedSource` to handle it nicer.
I'm aware we could also split the given source uri and encode only the path. Such an approach will fail on some obscure uri we didn't think of and therefore the most reliable way for me is to let the caller generate the encoded source.
> feat!: add NodeData.encodedSource 

- __tests__/newFileMenu.spec.ts
- lib/index.ts
- lib/newFileMenu.ts
- `templateName` is not used as the file creation is now handled by the developers themselves
- Renamed `if` to `enabled` to match other APIs
- To ensure we can have a custom order, I also added an order key
| Before | After with custom order |
|:---------:|:------:|
|![image](https://github.com/nextcloud-libraries/nextcloud-files/assets/14975046/4bd4af25-13e2-4b07-8f4b-924360784b2f)|![image](https://github.com/nextcloud-libraries/nextcloud-files/assets/14975046/75cfb7cb-03a6-44aa-8555-f8b417464b0f)|
> feat: support new file menu entry order

- __tests__/fileAction.spec.ts
- lib/fileAction.ts
- package.json
https://github.com/nextcloud/server/pull/41010
> feat: support nested actions

- __tests__/humanFileSize.spec.ts
- lib/humanfilesize.ts
(use binary sizes but decimal units)
For Nextcloud the current default is using binary sizes, like 1024 or 2048, but showing decimal units. Meaning 1024 bytes = 1 KB, like done on Windows and not like on Linux 1024 bytes = 1 KiB. There is also the option to show like on Apple: 1000 bytes = 1 KB and 1024 bytes = 1.024 KB
**This is (again) breaking**
> fix!(humanFileSize): Revert changes to default file sizes

- CHANGELOG.md
- package-lock.json
- package.json
[Full Changelog](https://github.com/nextcloud-libraries/nextcloud-files/compare/v3.0.0-beta.26...v3.0.0-beta.27)
* feat: support nested actions by @skjnldsv in https://github.com/nextcloud-libraries/nextcloud-files/pull/814
* fix(humanFileSize): Revert changes to default file sizes by @susnux in https://github.com/nextcloud-libraries/nextcloud-files/pull/822
* fix(newfilemenu): better sorting and proper fallback to displayName by @skjnldsv in https://github.com/nextcloud-libraries/nextcloud-files/pull/806
* chore(deps-dev): Bump @babel/traverse from 7.22.8 to 7.23.2 by @dependabot in https://github.com/nextcloud-libraries/nextcloud-files/pull/812
* chore(deps-dev): Bump @nextcloud/eslint-config from 8.3.0-beta.2 to 8.3.0 by @dependabot in …
> 3.0.0-beta.27

- lib/dav/dav.ts
https://github.com/nextcloud/server/pull/41202
> fix(dav): use of webdav library

- __tests__/files/node.spec.ts
- lib/files/node.ts
`dirname` and `path` both depend on the root property, but in case of the `webdav` endpoint the root is just `/` so in this case we need to remove the remote URL part first before we remove the root.
before | after
---|---
source: `http://foo.com/public.php/webdav/bar`<br>root: `/`<br>path: `/foo.com/public.php/webdav/bar`|source: `http://foo.com/public.php/webdav/bar`<br>root: `/`<br>path: `/bar`
> fix(Node): Handle slash as root path for public webdav endpoint

- lib/dav/dav.ts
Lightweight alternative to #848 
So this is not really an alternative but allow for doing it manually by users of this library, as otherwise you would need to patch the headers for every request. Also this is a bit more generic as it allows to set arbitrary additional headers.
> enh(dav): Allow to set custom headers when creating the DAV client

- CHANGELOG.md
- package-lock.json
- package.json
* enh(dav): Allow to set custom headers when creating the DAV client by @susnux in https://github.com/nextcloud-libraries/nextcloud-files/pull/849
* fix(Node): Handle slash as root path for public webdav endpoint by @susnux in https://github.com/nextcloud-libraries/nextcloud-files/pull/847
* fix(dav): davResultToNode real owner by @skjnldsv in https://github.com/nextcloud-libraries/nextcloud-files/pull/862
* Update webdav from 5.3.0 to 5.3.1
* Update dev dependencies
> chore: Prepare 3.1.0 release

- __tests__/dav/dav.spec.ts
- lib/dav/dav.ts
Owner can be transformed to a number by the webdav lib if it's only digits...
Also changed a few other typings to ensure we don't rely on inline types (we would have caught this sooner)
> fix(dav): various typings and owner string cast

- __tests__/dav/davProperties.spec.ts
- lib/dav/davProperties.ts
We moved those attributes to the `files_sharing` app, since we can disable the app.
Fix https://github.com/nextcloud/server/issues/43953
> fix(dav): remove sharing attributes from default dav fetch and change duplicate registration from `error` to `warn`

- __tests__/files/node.spec.ts
- lib/files/node.ts
> feat(files): allow updating attributes

- __tests__/fileAction.spec.ts
> fix(fileAction): cover parent getter in tests

- __tests__/dav/dav.spec.ts
- lib/dav/dav.ts
* Resolves https://github.com/nextcloud/server/issues/45420
> fix(dav): Add fallback for owner of dav nodes on public shares

- lib/index.ts
> fix: Export `NewMenuEntryCategory` from package

- CHANGELOG.md
- package-lock.json
- package.json
**Full Changelog**: https://github.com/nextcloud-libraries/nextcloud-files/compare/v3.3.0...v3.3.1
* fix: Export `NewMenuEntryCategory` from package by @susnux in https://github.com/nextcloud-libraries/nextcloud-files/pull/960
> chore: Prepare 3.3.1

- __tests__/files/node.spec.ts
- lib/files/node.ts
Attributes that are readonly should still be listed in the `attributes` getter, otherwise this is a hard breaking change as a lot of apps already depend on `attributes`. So instead only ensure that readonly attributes are skipped by the proxy handler.
> fix(Node): Do not drop readonly attributes but only forbid updating them

- __tests__/utils/fileSorting.spec.ts
Annoyed me that fileSorting was not 100% covered :sweat_smile:
> chore: Add test case for file sorting of same display name

- CHANGELOG.md
- package-lock.json
- package.json
We need a new minor version as the sorting feature was already merged. Releasing this for the Node attributes fix.
Maybe then also refactor server to use the new sorting :)
> chore: Prepare 3.4.0

- __tests__/files/file.spec.ts
- __tests__/files/node.spec.ts
- lib/files/node.ts
https://github.com/nextcloud/server/pull/45656#pullrequestreview-2096178862
Supersede https://github.com/nextcloud-libraries/nextcloud-files/pull/973
> fix(node): remove auto mtime update on attributes change and allow mtime set

- __tests__/dav/dav.spec.ts
- lib/dav/dav.ts
A negative fileid is returned by Nextcloud when something internally went wrong. In this case we should set the Node.status by default.
> fix(dav): Set `status` in `davResultToNode` when fileid is negative

- __tests__/utils/filename.spec.ts
- lib/index.ts
- lib/utils/filename.ts
For: https://github.com/nextcloud/server/blob/master/apps/files/src/utils/fileUtils.ts#L9
> feat: Add filename util `getUniqueName` to generate a unique name

- __tests__/utils/fileSorting.spec.ts
- lib/utils/fileSorting.ts
* Resolves https://github.com/nextcloud/server/issues/45829
We should not take the file extension into account while sorting, only if the basename is equal.
> fix: When sorting by filename the extension should only be considered if the basename is equal

- lib/files/file.ts
- lib/files/folder.ts
- lib/files/node.ts
- lib/index.ts
- lib/navigation/column.ts
- lib/navigation/navigation.ts
- lib/utils/fileSorting.ts
I would like to discuss this issue:
If you using those classes in Vue (e.g. in data) they will cause errors, as Vue unrefs data deeply and this causes all private fields to be stripped off from the interface. Passing one of those classes from data to a function that expects e.g. `Node` will then cause a Typescript error because the passed value is lacking the private fields.
So instead this provides interfaces that can be used whenever a parameter should be of one of those types.
Example of one of those errors:
---
Alternative: Cast them every time you use them, like
```ts
data() {
return { content: [] as Node[] }
},
methods: {
handleConflicts() {
getConflicts(nodes, this.content as Node[])
},
},
```
> feat: Export public interfaces of `Node`, `File` and `Folder`

- __tests__/navigation.spec.ts
- lib/navigation/navigation.ts
- package-lock.json
- package.json
This adds the native `EventTarget` class to the Navigation allowing to add listeners to it. Allowing to dispatch the `updateActive` event when the active navigation changed.
The idea is to make it reactive in a native / framework agnostic way.
> feat(navigation): Allow to listen for active navigation changes

- CHANGELOG.md
- package-lock.json
- package.json
**Full Changelog**: https://github.com/nextcloud-libraries/nextcloud-files/compare/v3.4.1...v3.5.0
* feat: Add filename util `getUniqueName` to generate a unique name \([\#986](https://github.com/nextcloud-libraries/nextcloud-files/pull/986)\)
* feat: Export public interfaces of `Node`, `File` and `Folder` \([\#976](https://github.com/nextcloud-libraries/nextcloud-files/pull/976)\)
* feat(navigation): Allow to listen for active navigation changes \([\#987](https://github.com/nextcloud-libraries/nextcloud-files/pull/987)\)
* fix(dav): Set `status` in `davResultToNode` when fileid is negative \([\#985](https://github.com/nextcloud-libraries/nextcloud-files/pull/985)\)
* fix: When sorting by filename the extension should only be considered if the basename is equal …
> chore: Prepare release of v3.5.0

- __tests__/dav/davProperties.spec.ts
- lib/dav/davProperties.ts
The two props were missing by default leading to problems where displayname is different from basename
> fix(dav): Add `displayname` and `creationdate` to default props

- __tests__/utils/fileSorting.spec.ts
- lib/utils/fileSorting.ts
Fix invalid usage of the display name property of DAV.
> fix(sorting): The display name attribute is called `displayname` not `displayName` for DAV

- README.md
See also https://github.com/nextcloud/documentation/pull/11947
> Update README.md to add more info about the webDAV client

- __mocks__/@nextcloud/router.js
- __tests__/dav/dav.spec.ts
- __tests__/files/node.spec.ts
- __tests__/utils/fileSorting.spec.ts
- lib/dav/dav.ts
- lib/files/node.ts
- lib/files/nodeData.ts
* chained on https://github.com/nextcloud-libraries/nextcloud-files/pull/1018
For legacy reasons a fallback is still used to move it from the `attributes` as otherwise this would be breaking.
> feat(node): Add `displayname` as top level attribute

- CHANGELOG.md
- package-lock.json
- package.json
[Full Changelog](https://github.com/nextcloud-libraries/nextcloud-files/compare/v3.5.1...v3.6.0)
* feat(filename): Improve filename validation to support Nextcloud 30 capabilities [\#1013](https://github.com/nextcloud-libraries/nextcloud-files/pull/1013) \([susnux](https://github.com/susnux)\)
* feat(node): Add `displayname` as top level attribute [\#1019](https://github.com/nextcloud-libraries/nextcloud-files/pull/1019) \([susnux](https://github.com/susnux)\)
* fix: `Node.move` should also adjust the displayname [\#1018](https://github.com/nextcloud-libraries/nextcloud-files/pull/1018) \([susnux](https://github.com/susnux)\)
* Update README.md to add more info about the webDAV client [\#1007](https://github.com/nextcloud-libraries/nextcloud-files/pull/1007) …
> chore: Prepare 3.6.0 release

- lib/dav/dav.ts
There is a bug in the webdav library that will cause e.g. `1` as a name to be interpreted as the number 1.
> fix(dav): Cast displayname to string in `resultToNode`

- lib/index.ts
- lib/utils/fileSorting.ts
- lib/utils/sorting.ts
Use sorting order consistently and export it as it is part of the public API.
> fix: Correctly export public API

- CHANGELOG.md
- package-lock.json
- package.json
[Full changelog](https://github.com/nextcloud-libraries/nextcloud-files/compare/v3.6.0...v3.7.0)
* feat: Implement API for file list filters [\#1027](https://github.com/nextcloud-libraries/nextcloud-files/pull/1027) \([susnux](https://github.com/susnux)\)
* fix(dav): Cast displayname to string in `resultToNode` [\#1028](https://github.com/nextcloud-libraries/nextcloud-files/pull/1028) \([susnux](https://github.com/susnux)\)
* fix: Correctly export public API [\#1026](https://github.com/nextcloud-libraries/nextcloud-files/pull/1026) \([susnux](https://github.com/susnux)\)
* chore(deps): Bump @nextcloud/paths from 2.1.0 to 2.2.0
> chore: Prepare v3.7.0

- lib/navigation/view.ts
New loadChildViews method added to be called to load child views
> feat: Allow registration of load child views callback on view

- CHANGELOG.md
- package-lock.json
- package.json
* feat: Allow registration of load child views callback on view by @Pytal in https://github.com/nextcloud-libraries/nextcloud-files/pull/1046
* chore(deps-dev): Bump @vitest/coverage-istanbul from 2.0.3 to 2.0.4 by @dependabot in https://github.com/nextcloud-libraries/nextcloud-files/pull/1033
* chore(deps-dev): Bump typedoc from 0.26.4 to 0.26.5 by @dependabot in https://github.com/nextcloud-libraries/nextcloud-files/pull/1031
* chore(deps): Bump @nextcloud/paths from 2.2.0 to 2.2.1 by @dependabot in https://github.com/nextcloud-libraries/nextcloud-files/pull/1037
* chore(deps): Bump @nextcloud/sharing from 0.2.2 to 0.2.3 by @dependabot in https://github.com/nextcloud-libraries/nextcloud-files/pull/1034
* chore(deps-dev): Bump vite from 5.3.4 to 5.3.5 by @dependabot in …
> chore: Release v3.8.0

- lib/navigation/view.ts
Make order optional for natural sorting
Needed for https://github.com/nextcloud/server/pull/47294
> feat: Allow views to be naturally sorted

- CHANGELOG.md
- package-lock.json
- package.json
[Full changelog](https://github.com/nextcloud-libraries/nextcloud-files/compare/v3.8.0...v3.9.0)
* feat: Allow views to be naturally sorted by @Pytal in https://github.com/nextcloud-libraries/nextcloud-files/pull/1053
* chore(deps-dev): Bump @nextcloud/vite-config from 2.1.0 to 2.2.2 by @dependabot in https://github.com/nextcloud-libraries/nextcloud-files/pull/1048
* chore(deps-dev): Bump vite from 5.3.5 to 5.4.0 by @dependabot in https://github.com/nextcloud-libraries/nextcloud-files/pull/1051
* chore(deps): Bump webdav from 5.7.0 to 5.7.1 by @dependabot in https://github.com/nextcloud-libraries/nextcloud-files/pull/1049
* chore(deps-dev): Bump @types/node from 22.1.0 to 22.2.0 by @dependabot in https://github.com/nextcloud-libraries/nextcloud-files/pull/1050
* chore(deps): Bump is-svg …
> chore: Release v3.9.0

- __tests__/fileAction.spec.ts
- lib/fileAction.ts
Makes the action be shown more prominently marked as destructive. Required for https://github.com/nextcloud/server/issues/46732
> feat(FileAction): Allow to set `destructive` flag

- lib/fileListFilters.ts
To use a user avatar instead of an icon - used by the "accounts filter".
Forgot to upstream this before :see_no_evil:
> fix: Document optional `user` property of FileListFilterChip

- lib/files/file.ts
- lib/files/folder.ts
- lib/files/node.ts
- lib/index.ts
- tsconfig.json
For https://github.com/nextcloud/server/pull/47959
> feat: Allow cloning a node

- __tests__/fileListAction.spec.ts
- __tests__/view.spec.ts
- lib/fileListAction.ts
- lib/index.ts
- lib/navigation/view.ts
- window.d.ts
Adds new view actions
Part of https://github.com/nextcloud/server/issues/5534
> feat: Allow registering actions for a file listing

- __tests__/dav/dav.spec.ts
- lib/dav/dav.ts
See https://github.com/nextcloud/server/pull/49225
> fix(dav): crtime parsing and invalid date handling

- __tests__/fileListAction.spec.ts
- lib/fileListAction.ts
Part of https://github.com/nextcloud/server/issues/5534
> feat: Add current folder context for file list actions

- README.md
- __tests__/dav/dav.spec.ts
- __tests__/dav/davPermissions.spec.ts
- __tests__/dav/davProperties.spec.ts
- __tests__/dav/public-shares.spec.ts
- lib/dav/dav.ts
- lib/dav/davPermissions.ts
- lib/dav/davProperties.ts
- lib/dav/index.ts
- lib/index.ts
- package.json
- vite.config.ts
What do you think of this idea?
---
* Implements: https://github.com/nextcloud-libraries/nextcloud-files/issues/1015
This splits the package into modules:
1. The default one (`@nextcloud/files`) which provides general classes to work with the Node classes we use nearly everywhere
2. DAV utils (`@nextcloud/files/dav`) which provides WebDAV related utils
3. File list related utils (actions, filters, columns)
4. Navigation related utils
5. General purpose small helper functions (utils)
For legacy reasons to not make this a breaking release the DAV utils are exported with their prefixed names in the default module, but this will be then removed with the next major version.
> refactor: Scope package into modules

- __tests__/fileListFilter.spec.ts
- lib/fileListFilters.ts
This allows the files app to reset filters if needed (e.g. on navigation) instead all filters to listen  to different events.
> feat: Add `reset` method to file list filters

- CHANGELOG.md
- package-lock.json
- package.json
3.10.0 was never released, as the `package.json` contained the wrong version.
So lets fix this by "re-releasing" (first time releasing :thinking: ) it.
Ideally I would like to also merge this in:
---
[Full changelog](https://github.com/nextcloud-libraries/nextcloud-files/compare/v3.9.2...v3.10.0)
* Scope package into modules [\#1025](https://github.com/nextcloud-libraries/nextcloud-files/pull/1025) \([susnux](https://github.com/susnux)\)  
All DAV related functions are now moved to the `@nextcloud/files/dav` module.
You can still import them from the main entrypoint, but this is now deprecated.
New functions will only be available in the `@nextcloud/files/dav` entrypoint.
* feat: Add current folder context for file list actions [\#1113](https://github.com/nextcloud-libraries/nextcloud-file …
> chore: Prepare release of v3.10.0

- vite.config.ts
* fix: https://github.com/nextcloud-libraries/nextcloud-files/issues/1127
The rollup only works for single entry point and will duplicate declarations.
See: https://api-extractor.com/pages/setup/configure_rollup/#an-important-limitation
> fix: Do not rollup types

- __tests__/fileListAction.spec.ts
- lib/fileListAction.ts
Requested in https://github.com/nextcloud/server/pull/49171
> feat: Allow omitting icon for file list actions

- lib/fileListAction.ts
https://github.com/nextcloud/server/pull/49171#issuecomment-2538551777
> fix: ensure FileListAction return `bool|null` on `exec`

- package.json
* Resolves https://github.com/nextcloud-libraries/nextcloud-files/issues/1174
> fix: Correctly export DAV types

- CHANGELOG.md
- package-lock.json
- package.json
* fix: ensure FileListAction return `bool|null` on `exec` [\#1145](https://github.com/nextcloud-libraries/nextcloud-files/pull/1145) \([skjnldsv](https://github.com/skjnldsv)\)
* fix: Correctly export DAV types [\#1176](https://github.com/nextcloud-libraries/nextcloud-files/pull/1176) \([susnux](https://github.com/susnux)\)
* fix(deps): typedoc-plugin-missing-exports as dev dependency [\#1183](https://github.com/nextcloud-libraries/nextcloud-files/pull/1183) \([max-nextcloud](https://github.com/max-nextcloud)\)
* Updated development dependencies
* chore(deps): Bump `@nextcloud/sharing` to 0.2.4
* ci: Update workflows from organization [\#1177](https://github.com/nextcloud-libraries/nextcloud-files/pull/1177) \([susnux](https://github.com/susnux)\)
> chore: Prepare v3.10.2

- __tests__/files/file.spec.ts
- __tests__/files/node.spec.ts
- lib/files/node.ts
Our storage backend doesn't update it.
We have a discrepancy. 
So if I rename a file, which changes the last mtime with the current state of this library, then updating from the backend again (refreshing for example) shows the old date again.
> fix: do not update mtime on move/rename

- __tests__/utils/fileSorting.spec.ts
- lib/dav/dav.ts
- lib/utils/fileSorting.ts
Needed for https://github.com/nextcloud/server/issues/49140
Because the Trashbin view use a custom attribute key to sort https://github.com/nextcloud/server/blob/aac5859444a54e9774b794ad4b29486bbb384ea7/apps/files_trashbin/src/files_views/trashbinView.ts#L26
> fix(sorting): also check attributes

- lib/actions/fileAction.ts
- lib/actions/index.ts
This allows to define a hotkey which will trigger the action for the currently active / selected file.
> feat(actions): allow to define hotkey for file action

- package.json
dependabot uses `corepack` for all updates of node dependencies. The problem here is that `corepack` breaks if the
`devEngines.packageManager` does not define a **full semantic version** meaning it does not support semantic ranges.
We can work around this by just using the array syntax with only one entry.
For reference the *corepack* bug report: https://github.com/nodejs/corepack/issues/729
> chore: work around bug in `corepack` blocking dependency updates
